version: '2'

services:
  drone-server:
    image: drone/drone:0.7
    ports:
      - "8080:8000"
    volumes:
      - $HOME/Desktop/docker-drone:/var/lib/drone
    restart: always
    environment:
      - DRONE_DEBUG=false
      - DRONE_ADMIN=okapie
      - DRONE_OPEN=true # User registration: true=enabled, false=unenabled
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_URL=${DRONE_GITHUB_URL}
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_GITHUB_SCOPE=repo,repo:status,user:email,read:org
      - DRONE_GITHUB_PRIVATE_MODE=true
      - DRONE_GITHUB_MERGE_REF=true
      - DRONE_GITHUB_SKIP_VERIFY=true
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_GITHUB_CONTEXT=continuous-integration/drone
  drone-agent:
    image: drone/drone:0.7
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_DEBUG=false
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_MAX_PROCS=1
